-- Category updates for ApertureLeadership staging
UPDATE session_images SET album_category_id = 1 WHERE title = 'Art Figures France 2020';
UPDATE session_images SET album_category_id = 3 WHERE title = 'Atacama Volcanic Springs Chile 2017';
UPDATE session_images SET album_category_id = 3 WHERE title = 'Badiyah Dune Oman 2010';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Balcony Havana Cuba 2010';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Berlin Cemetary Germany 2003';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Berlin Clock Germany 2003';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Berlin Traffic Box Germany 2003';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Berlin Wall Germany 2003';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Bicycles Cochin India 2015';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Bicycles Florence Italy 1997';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Big Ben London UK 2000';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Brancusi Sleeping Muse Paris France 2024';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Bubble London South Bank UK 2013';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Budapest Castle Hungary 2013';
UPDATE session_images SET album_category_id = 3 WHERE title = 'Cave Dwellings Oman 2014';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Cemetary Atacama Chile 2016';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Che Havana Facade Cuba 2014';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Church Amorgos Greece 2022';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Cliff Church Amorogos Greece 2022';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Coliseum Arles France 2021';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Dancing in Northern Greece 2022';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Djoser Tomb Egypt 2014';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Elevators Heathrow UK 2024';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Farmer Burkina Faso 2015';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Fernand Leger Museum Biot France 2025';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Giacometti Venice Italy 2013';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Giant Buddah Kamakura Japan 2007';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Guggenheim New York USA 2022';
UPDATE session_images SET album_category_id = 3 WHERE title = 'Half Dome Yosemite USA 2015';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Halong Family Vietnam 2013';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Hamer Woman Omo Ethiopia 2014';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Hand of Buddha Kyoto Japan 2013';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Koi Kyoto Japan 2013';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Lions Chauvet Cave France 2021';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Lost City Trail Colombia 2024';
UPDATE session_images SET album_category_id = 3 WHERE title = 'Meteora Monastery Greece 2020';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Monkey Temple Rajasthan India 2010';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Musee D'Orsay Paris France 1995';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Pere Lachaise Cemetary Paris Farnce 2003';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Priest Amorgos Greece 2022';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Reichstag Dome Berlin Germany 2003';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Reichstag Mirrors Berlin Germany 2003';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Rice Paddy Ubud 2022';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Rodin Mural Bangkok Thailand 2024';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Rosetta Stone British Museum London UK 2015';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Teppanyaki Tokyo Japan 2023';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Tokyo Station Japan 2023';
UPDATE session_images SET album_category_id = 3 WHERE title = 'Van Gogh's Bedroom St Remy France 2020';
UPDATE session_images SET album_category_id = 5 WHERE title = 'Venice Biennale Hand Italy 2018';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Venice Biennale Sculptures Italy 2018';
UPDATE session_images SET album_category_id = 4 WHERE title = 'Village Elder Tanzania 2015';
UPDATE session_images SET album_category_id = 1 WHERE title = 'Waterfall Yosemite USA 2016';
UPDATE session_images SET album_category_id = 2 WHERE title = 'Womens Monument Boston USA 2022';
